# Data Cleaning in Pandas

In [5]:
import pandas as pd

In [7]:
df = pd.read_excel(r"E:\\pandas\Customer Call List.xlsx")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [27]:
df = pd.read_excel(r"E:\\pandas\Customer Call List.xlsx")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [33]:
df.drop_duplicates()
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [45]:
df=df.drop(columns ="Not_Useful_Column")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [97]:
df.drop_duplicates()
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes
2,1003,Walter,White,,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,,1209 South Street,No,No
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N
20,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N

In [55]:
df["Last_Name"]=df["Last_Name"].str.lstrip("...")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [61]:
#df["Last_Name"]=df["Last_Name"].str.lstrip("/")
#df["Last_Name"]=df["Last_Name"].str.lstrip("_")

df["Last_Name"]=df["Last_Name"].str.strip("123._/")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [11]:
#df["Phone_Number"] = df["Phone_Number"].str.replace('[^a-zA-Z0-9]', '', regex=True)
#df["Phone_Number"].apply(lambda x: x[0:3]+ '-' + x[3:6] + '-' + x[6:10]) 
#df["Phone_Number"] = df["Phone_Number"].apply(lambda x: str(x))

#df["Phone_Number"] = df["Phone_Number"].apply(lambda x: x[0:3]+ '-' + x[3:6] + '-' + x[6:10]) 
df["Phone_Number"] = df["Phone_Number"].str.replace('nan--','')
df["Phone_Number"] = df["Phone_Number"].str.replace('Na--','')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,NaN,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,NaN,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,NaN,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [9]:
#df["Do_Not_Contact"] = df["Do_Not_Contact"].fillna('')
df["Do_Not_Contact"] = df["Do_Not_Contact"].replace("NaN", '', regex=True)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [17]:
df["Phone_Number"] = df["Phone_Number"].str.replace('Nan','')
df["Phone_Number"] = df["Phone_Number"].str.replace('N/a','')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,NaN,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,NaN,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,NaN,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [39]:
df["Phone_Number"] = df["Phone_Number"].str.replace('|', '-', regex=False)

In [41]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,1235455421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,1235432345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,3047622467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,1235455421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,1235432345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,3047622467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,1235455421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [43]:
df["Phone_Number"] = df["Phone_Number"].str.replace(r'(\d{3})(\d{3})(\d{4})', r'\1-\2-\3', regex=True)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [49]:
 df["Last_Name"] = df["Last_Name"].str.replace('/', '', regex=False)
df["Last_Name"] = df["Last_Name"].str.replace('...', '', regex=False)
df["Last_Name"] = df["Last_Name"].str.replace('_', '', regex=False)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,False
2,1003,Walter,White,,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [51]:
df["Do_Not_Contact"] = df["Do_Not_Contact"].str.replace('Yes','Y')
df["Do_Not_Contact"] = df["Do_Not_Contact"].str.replace('No','N')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,N,True
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Y,False
2,1003,Walter,White,,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Y,True
6,1007,Jeff,Winger,,1209 South Street,No,N,False
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,False
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,N,True
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,N,True
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,N,False
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,N,False
17,1018,Clark,Kent,,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,,N/a,N/a,Y,True
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [53]:
df["Paying Customer"] = df["Paying Customer"].str.replace('Yes','Y')
df["Paying Customer"] = df["Paying Customer"].str.replace('No','N')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,True
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,N,Y,False
2,1003,Walter,White,,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,True
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Y,Y,True
6,1007,Jeff,Winger,,1209 South Street,N,N,False
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,False
8,1009,Gandalf,NaN,,123 Middle Earth,Y,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,True
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,N,True
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,False
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,False
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,False
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,False
17,1018,Clark,Kent,,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,,N/a,N/a,Y,True
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,True
20,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,True

In [55]:
df = df.fillna('')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,True
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,N,Y,False
2,1003,Walter,White,,298 Drugs Driveway,N,,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,True
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Y,Y,True
6,1007,Jeff,Winger,,1209 South Street,N,N,False
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,False
8,1009,Gandalf,,,123 Middle Earth,Y,,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,True
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,N,True
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,False
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,False
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,False
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,False
17,1018,Clark,Kent,,3498 Super Lane,Y,,True
18,1019,Creed,Braton,,N/a,N/a,Y,True
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,True
20,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,True

In [57]:
df["Paying Customer"] = df["Paying Customer"].str.replace('N/a','')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,True
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,N,Y,False
2,1003,Walter,White,,298 Drugs Driveway,N,,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,True
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Y,Y,True
6,1007,Jeff,Winger,,1209 South Street,N,N,False
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,False
8,1009,Gandalf,,,123 Middle Earth,Y,,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,True
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,N,True
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,False
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,False
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,False
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,False
17,1018,Clark,Kent,,3498 Super Lane,Y,,True
18,1019,Creed,Braton,,N/a,,Y,True
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,True
20,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,True

In [61]:
df["Address"] = df["Address"].str.replace('N/a','')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,Address\t
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,True,"123 Shire Lane, Shire"
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,N,Y,False,93 West Main Street
2,1003,Walter,White,,298 Drugs Driveway,N,,True,298 Drugs Driveway
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,True,"980 Paper Avenue, Pennsylvania, 18503"
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,True,123 Dragons Road
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Y,Y,True,768 City Parkway
6,1007,Jeff,Winger,,1209 South Street,N,N,False,1209 South Street
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,False,98 Clue Drive
8,1009,Gandalf,,,123 Middle Earth,Y,,False,123 Middle Earth
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,True,"25th Main Street, New York"
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,N,True,"612 Shire Lane, Shire"
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,,True,2394 Hogwarts Avenue
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,False,2039 Main Street
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,False,343 City Parkway
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,False,214 HR Avenue
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,False,2395 Hogwarts Avenue
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,False,"121 Paper Avenue, Pennsylvania"
17,1018,Clark,Kent,,3498 Super Lane,Y,,True,3498 Super Lane
18,1019,Creed,Braton,,,,Y,True,
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,True,"910 Tatooine Road, Tatooine"
20,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,True,"910 Tatooine Road, Tatooine"

In [63]:
for x in df.index:
    if df.loc[x,"Do_Not_Contact"] == 'Y':
        df.drop(x, inplace =True)

df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,Address\t
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,True,"123 Shire Lane, Shire"
2,1003,Walter,White,,298 Drugs Driveway,N,,True,298 Drugs Driveway
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,True,123 Dragons Road
6,1007,Jeff,Winger,,1209 South Street,N,N,False,1209 South Street
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,False,98 Clue Drive
8,1009,Gandalf,,,123 Middle Earth,Y,,False,123 Middle Earth
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,True,"25th Main Street, New York"
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,N,True,"612 Shire Lane, Shire"
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,,True,2394 Hogwarts Avenue
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,False,2039 Main Street
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,False,343 City Parkway
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,False,214 HR Avenue
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,False,2395 Hogwarts Avenue
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,False,"121 Paper Avenue, Pennsylvania"
17,1018,Clark,Kent,,3498 Super Lane,Y,,True,3498 Super Lane
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,True,"910 Tatooine Road, Tatooine"
20,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,True,"910 Tatooine Road, Tatooine"

In [65]:
for x in df.index:
    if df.loc[x, "Phone_Number"] == '':
        df.drop(x, inplace =True)

df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,Address\t
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,True,"123 Shire Lane, Shire"
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,True,123 Dragons Road
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,False,98 Clue Drive
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,True,"25th Main Street, New York"
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,False,2039 Main Street
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,False,343 City Parkway
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,False,214 HR Avenue
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,False,2395 Hogwarts Avenue
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,False,"121 Paper Avenue, Pennsylvania"
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,True,"910 Tatooine Road, Tatooine"
20,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,True,"910 Tatooine Road, Tatooine"

In [67]:
df = df.reset_index(drop = True)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,Address\t
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,True,"123 Shire Lane, Shire"
1,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,True,123 Dragons Road
2,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,False,98 Clue Drive
3,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,True,"25th Main Street, New York"
4,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,False,2039 Main Street
5,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,False,343 City Parkway
6,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,False,214 HR Avenue
7,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,False,2395 Hogwarts Avenue
8,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,False,"121 Paper Avenue, Pennsylvania"
9,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,True,"910 Tatooine Road, Tatooine"
10,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,True,"910 Tatooine Road, Tatooine"